name: Build Docker Container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build IP service Container
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        file: ./Dockerfile
        target: production
        tags: ghcr.io/ucsd-e4e/mmict-ip_service:latest